### Localhost

POST http://localhost:3000/users
Content-Type: application/json

{
  "name": "João Silva",
  "email": "joao.silva@email.com",
  "password": "123456"
}

### Railway

POST https://aulabanco.up.railway.app/users
Content-Type: application/json

{
  "name": "Luiz henrique",
  "email": "luiz.henrique@email.com",
  "password": "40028922"
}
